# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Less than Eight Minutes
email: eight-minutes@rawiron.io
description: > # this means to ignore newlines until "baseurl:"
  How I explain it to myself in a concise way.
  Computer systems and infrastructure.
  Programming languages.
  Programming.
  Data Processing, Machine Learning.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rawiron.io" # the base hostname & protocol for your site
twitter_username: rawiron
github_username:  rawiron

# Build settings
markdown: kramdown
